/* Generated By:JJTree: Do not edit this line. ASTarithexprprime.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Demo;

public
class ASTarithexprprime extends SimpleNode {
  public ASTarithexprprime(int id) {
    super(id);
  }

  public ASTarithexprprime(CMinusParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CMinusParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=955c130200e1179c597392b2b888826a (do not edit this line) */
