/* Generated By:JJTree: Do not edit this line. ASTcompoundstmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Demo;

public
class ASTcompoundstmt extends SimpleNode {
  public ASTcompoundstmt(int id) {
    super(id);
  }

  public ASTcompoundstmt(CMinusParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CMinusParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=13c2b4103596539fc2635d688f362bf7 (do not edit this line) */
