/* Generated By:JJTree: Do not edit this line. ASTerrorSkipTo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Demo;

public
class ASTerrorSkipTo extends SimpleNode {
  public ASTerrorSkipTo(int id) {
    super(id);
  }

  public ASTerrorSkipTo(CMinusParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CMinusParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7253839b3619a511b67bfc1716ea7f86 (do not edit this line) */
