/* Generated By:JJTree: Do not edit this line. ASTgreaterequal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Demo;

public
class ASTgreaterequal extends SimpleNode {
  public ASTgreaterequal(int id) {
    super(id);
  }

  public ASTgreaterequal(CMinusParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CMinusParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4f968b307534a2e1c4653b863344b6e8 (do not edit this line) */
