/* Generated By:JJTree: Do not edit this line. ASTlessequal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Demo;

public
class ASTlessequal extends SimpleNode {
  public ASTlessequal(int id) {
    super(id);
  }

  public ASTlessequal(CMinusParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CMinusParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6f5be1ef7d5ed7ce1c6b86b9f4d27d65 (do not edit this line) */
