/* Generated By:JJTree: Do not edit this line. ASTmultexprprime.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Demo;

public
class ASTmultexprprime extends SimpleNode {
  public ASTmultexprprime(int id) {
    super(id);
  }

  public ASTmultexprprime(CMinusParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CMinusParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c2122660eb096d689bc9f6800fdf7643 (do not edit this line) */
