/* Generated By:JJTree: Do not edit this line. ASTrealnumber.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Demo;

public
class ASTrealnumber extends SimpleNode {
  public ASTrealnumber(int id) {
    super(id);
  }

  public ASTrealnumber(CMinusParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CMinusParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1e0bbbf3aac5896f9c7f64f66e74ed47 (do not edit this line) */
