/* Generated By:JJTree: Do not edit this line. ASTwhilestmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Demo;

public
class ASTwhilestmt extends SimpleNode {
  public ASTwhilestmt(int id) {
    super(id);
  }

  public ASTwhilestmt(CMinusParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CMinusParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c020563d528343beb6f921ea9acb82d0 (do not edit this line) */
