/* Generated By:JavaCC: Do not edit this line. CMinusParserTreeConstants.java Version 5.0 */
package Demo;

public interface CMinusParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTMT = 1;
  public int JJTCOMPOUNDSTMT = 2;
  public int JJTLB = 3;
  public int JJTRB = 4;
  public int JJTERRORSKIPTO = 5;
  public int JJTSTMTS = 6;
  public int JJTIFSTMT = 7;
  public int JJTTHENN = 8;
  public int JJTELS = 9;
  public int JJTIFF = 10;
  public int JJTWHILESTMT = 11;
  public int JJTLOOP = 12;
  public int JJTLEFTB = 13;
  public int JJTRIGHTB = 14;
  public int JJTASSGSTMT = 15;
  public int JJTASSI = 16;
  public int JJTDECL = 17;
  public int JJTSEMICOL = 18;
  public int JJTTYPE = 19;
  public int JJTINTEGER = 20;
  public int JJTREALNUMBER = 21;
  public int JJTLIST = 22;
  public int JJTIDENTITY = 23;
  public int JJTLIST1 = 24;
  public int JJTCOMMA = 25;
  public int JJTBOOLEXPR = 26;
  public int JJTBOOLOP = 27;
  public int JJTLESSTHAN = 28;
  public int JJTGREATERTHAN = 29;
  public int JJTLESSEQUAL = 30;
  public int JJTGREATEREQUAL = 31;
  public int JJTEQUAL = 32;
  public int JJTARITHEXPR = 33;
  public int JJTARITHEXPRPRIME = 34;
  public int JJTPL = 35;
  public int JJTMI = 36;
  public int JJTMULTEXPR = 37;
  public int JJTMULTEXPRPRIME = 38;
  public int JJTSTA = 39;
  public int JJTOB = 40;
  public int JJTSIMPLEEXPR = 41;
  public int JJTNUMBER = 42;
  public int JJTEPSILON = 43;


  public String[] jjtNodeName = {
		  "Program",
		    "stmt",
		    "compoundstmt",
		    "{",
		    "}",
		    "errorSkipTo",
		    "stmts",
		    "ifstmt",
		    "then",
		    "else",
		    "if",
		    "whilestmt",
		    "while",
		    "(",
		    ")",
		    "assgstmt",
		    "=",
		    "decl",
		    ";",
		    "type",
		    "int",
		    "real",
		    "list",
		    "identity",
		    "list1",
		    ",",
		    "boolexpr",
		    "boolop",
		    "<",
		    ">",
		    "<=",
		    ">=",
		    "==",
		    "arithexpr",
		    "arithexprprime",
		    "+",
		    "-",
		    "multexpr",
		    "multexprprime",
		    "*",
		    "/",
		    "simpleexpr",
		    "number",
		    "ε",
  };
}
/* JavaCC - OriginalChecksum=de43a8af8383d76f40ea6d890a68a73d (do not edit this line) */
