/* Generated By:JavaCC: Do not edit this line. CMinusParserVisitor.java Version 5.0 */
package Demo;

public interface CMinusParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTstmt node, Object data);
  public Object visit(ASTcompoundstmt node, Object data);
  public Object visit(ASTlb node, Object data);
  public Object visit(ASTrb node, Object data);
  public Object visit(ASTerrorSkipTo node, Object data);
  public Object visit(ASTstmts node, Object data);
  public Object visit(ASTifstmt node, Object data);
  public Object visit(ASTthenn node, Object data);
  public Object visit(ASTels node, Object data);
  public Object visit(ASTiff node, Object data);
  public Object visit(ASTwhilestmt node, Object data);
  public Object visit(ASTloop node, Object data);
  public Object visit(ASTleftb node, Object data);
  public Object visit(ASTrightb node, Object data);
  public Object visit(ASTassgstmt node, Object data);
  public Object visit(ASTassi node, Object data);
  public Object visit(ASTdecl node, Object data);
  public Object visit(ASTsemicol node, Object data);
  public Object visit(ASTtype node, Object data);
  public Object visit(ASTinteger node, Object data);
  public Object visit(ASTrealnumber node, Object data);
  public Object visit(ASTlist node, Object data);
  public Object visit(ASTidentity node, Object data);
  public Object visit(ASTlist1 node, Object data);
  public Object visit(ASTcomma node, Object data);
  public Object visit(ASTboolexpr node, Object data);
  public Object visit(ASTboolop node, Object data);
  public Object visit(ASTlessthan node, Object data);
  public Object visit(ASTgreaterthan node, Object data);
  public Object visit(ASTlessequal node, Object data);
  public Object visit(ASTgreaterequal node, Object data);
  public Object visit(ASTequal node, Object data);
  public Object visit(ASTarithexpr node, Object data);
  public Object visit(ASTarithexprprime node, Object data);
  public Object visit(ASTpl node, Object data);
  public Object visit(ASTmi node, Object data);
  public Object visit(ASTmultexpr node, Object data);
  public Object visit(ASTmultexprprime node, Object data);
  public Object visit(ASTsta node, Object data);
  public Object visit(ASTob node, Object data);
  public Object visit(ASTsimpleexpr node, Object data);
  public Object visit(ASTnumber node, Object data);
  public Object visit(ASTepsilon node, Object data);
}
/* JavaCC - OriginalChecksum=f82d20629487475c5fc994a7c74af082 (do not edit this line) */
