/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */
package test;

public interface MyNewGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTMAINSTATEMENT = 2;
  public int JJTSTATEMENT = 3;
  public int JJTSEQUENCESTATEMENT = 4;
  public int JJTDECLARATION = 5;
  public int JJTCOPY = 6;
  public int JJTIFSTATEMENT = 7;
  public int JJTELSESTATEMENT = 8;
  public int JJTASSIGN = 9;
  public int JJTBOOLEXPRESSION = 10;
  public int JJTANDEXP = 11;
  public int JJTNOTEXP = 12;
  public int JJTCONDITION = 13;
  public int JJTTERM = 14;
  public int JJTUNARY = 15;
  public int JJTWHILE = 16;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "MainStatement",
    "Statement",
    "SequenceStatement",
    "declaration",
    "copy",
    "IfStatement",
    "ElseStatement",
    "assign",
    "BoolExpression",
    "AndExp",
    "NotExp",
    "Condition",
    "term",
    "unary",
    "While",
  };
}
/* JavaCC - OriginalChecksum=6db7047babd91ff7ead014c4ef1f41b3 (do not edit this line) */
